site_name: sundicide
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - scala
nav:
    - Home: index.md
    - Docker: docker.md
    - Scala:
        - 'Coursera/fpp-in-scala': scala/fpp-in-scala.md
        - 'Coursera/fpd-in-scala': scala/fpd-in-scala.md
        - 'Coursera/parallel-programming': scala/parallel-programming.md
        - 'Coursera/bigdata-analysis-spark': scala/bigdata-analysis-with-scala-and-spark.md
        - 'My Scala': scala/my-scala.md
        - 'My Spark': scala/my-spark.md
    - Rust:
        - '01-start-rust': rust/01-start-rust.md