site_name: sundicide
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - scala
nav:
    - Home: index.md
    - Scala:
        - 'Coursera/fpp-in-scala': scala/fpp-in-scala.md
        - 'Coursera/fpd-in-scala': scala/fpd-in-scala.md